import HSFormal.LTheory.Cylinder
import HSFormal.LTheory.KaroubiFiltration
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# The concrete L-group `Lconc` (L-theory module M5)

For an `InvCat` `A`, `Lconc A N` is the abelian group generated by the `N`-dimensional strictly
symmetric Poincaré complexes in `Kar A`, modulo `[P ⊕_b Q] = [P] + [Q]` for unitary bicones `b`
and `[P] = 0` for null-cobordant `P` (`blueprint/L-theory-design.md` §2.3).  By design §2.1 it is
Ranicki's `L^p_N(A)` for `N ≥ 0`; since complexes are supported in `[0, N]`, `Lconc A N = 0` for
`N < 0` (design, audit addendum).

* `Lconc.cls`: the class of a complex; it is additive for any bicone family (`cls_sum`),
  `cls_neg`, invariant under homotopy isometries (`cls_eq_of_isometry`, [Ran89, 3.10]) and
  cobordisms, and every element is a class (`cls_surjective`).
* `SymPoincare.cut`: the summand cut out by a `φ`-self-adjoint chain idempotent; `cls` is additive
  along orthogonal decompositions (`cls_cut_sum`).
* `Lconc.map`: functoriality along `InvFunctor`s, invariance under unitary natural isomorphisms
  (`map_eq_of_unitaryIso`) and additivity along finite unitary sums (`map_finSum`).
* `InvCat.pi`, `InvCat.finSupp`: products and finite-support sums of `InvCat`s, with the
  comparison maps `Lconc (∏ Aᵢ) → ∏ Lconc Aᵢ` (bijective for finite index sets) and
  `Lconc (⊕ Aᵢ) → ∏ Lconc Aᵢ` (injective, with finitely supported image).
-/

namespace HSFormal.LTheory

open CategoryTheory Category Limits Preadditive HomologicalComplex HSFormal.Compression

noncomputable section

universe v u

section Cut

variable {V : Type u} [Category.{v} V] [Preadditive V] {J : StrictInvolution V} {N : ℤ}

namespace SymPoincare

/-- A homotopy isometry given by strict identities. -/
def HomotopyIsometry.ofEq {P Q : SymPoincare J N} (f : P.C ⟶ Q.C) (g : Q.C ⟶ P.C)
    (f_kar : P.p ≫ f ≫ Q.p = f) (g_kar : Q.p ≫ g ≫ P.p = g) (fg : f ≫ g = P.p)
    (gf : g ≫ f = Q.p) (conj : dualHom J N f ≫ P.φ ≫ f = Q.φ) : HomotopyIsometry P Q :=
  ⟨f, g, f_kar, g_kar, .ofEq fg, .ofEq gf, .ofEq conj⟩

/-- Sums along different bicone families are isometric. -/
def sumIsometry (P Q : SymPoincare J N) (b b' : ∀ r, BinaryBicone (P.C.X r) (Q.C.X r)) :
    HomotopyIsometry (P.sum Q b) (P.sum Q b') := by
  refine .ofEq (sumFst b ≫ P.p ≫ sumInl b' + sumSnd b ≫ Q.p ≫ sumInr b')
    (sumFst b' ≫ P.p ≫ sumInl b + sumSnd b' ≫ Q.p ≫ sumInr b) ?_ ?_ ?_ ?_ ?_ <;>
    simp [add_comp, comp_add]

variable (P : SymPoincare J N)

/-- A chain idempotent `e` of `P` commuting with `p` and self-adjoint for `φ` (`e^* φ = φ e`). -/
structure IsReducing (e : P.C ⟶ P.C) : Prop where
  idem : e ≫ e = e
  comm : e ≫ P.p = P.p ≫ e
  adj : dualHom J N e ≫ P.φ = P.φ ≫ e

namespace IsReducing

attribute [reassoc] idem comm adj

variable {P} {e e' : P.C ⟶ P.C}

lemma kar (he : P.IsReducing e) : P.p ≫ e ≫ P.p ≫ e = P.p ≫ e := by
  rw [he.comm_assoc, P.p_idem_assoc, he.idem]

lemma zero : P.IsReducing 0 := ⟨by simp, by simp, by simp⟩

/-- The sum of orthogonal reducing idempotents. -/
lemma add (he : P.IsReducing e) (he' : P.IsReducing e') (h : e ≫ e' = 0) (h' : e' ≫ e = 0) :
    P.IsReducing (e + e') :=
  ⟨by simp [add_comp, comp_add, he.idem, he'.idem, h, h'],
    by simp [add_comp, comp_add, he.comm, he'.comm],
    by simp [add_comp, comp_add, he.adj, he'.adj]⟩

/-- Finite sums of pairwise orthogonal reducing idempotents are reducing. -/
lemma sum {ι : Type*} (s : Finset ι) {e : ι → (P.C ⟶ P.C)} (he : ∀ i, P.IsReducing (e i))
    (horth : ∀ i j, i ≠ j → e i ≫ e j = 0) : P.IsReducing (∑ i ∈ s, e i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using zero
  | insert a s ha ih =>
    rw [Finset.sum_insert ha]
    refine (he a).add ih ?_ ?_
    · rw [comp_sum]; exact Finset.sum_eq_zero fun i hi ↦ horth a i (by rintro rfl; exact ha hi)
    · rw [sum_comp]; exact Finset.sum_eq_zero fun i hi ↦ horth i a (by rintro rfl; exact ha hi)

end IsReducing

/-- The summand `(C, pe, φe)` cut out by a reducing idempotent `e`. -/
@[simps, reducible]
def cut {e : P.C ⟶ P.C} (he : P.IsReducing e) : SymPoincare J N where
  C := P.C
  p := P.p ≫ e
  p_idem := by rw [assoc, he.kar]
  support r hr := by simp [P.support r hr]
  φ := P.φ ≫ e
  φ_kar := by
    simp only [dualHom_comp, assoc, P.dualHom_p_comp_φ_assoc, he.adj_assoc, he.idem_assoc]
    rw [he.comm_assoc, he.idem, P.φ_comp_p_assoc]
  symm := by
    have h : dualHom J N e ≫ P.φ ≫ e = P.φ ≫ e := by rw [he.adj_assoc, he.idem]
    exact h ▸ P.symm.conj e
  poincare := by
    obtain ⟨ψ, hψ, ⟨H₁⟩, ⟨H₂⟩⟩ := P.poincare
    have hψ' : P.p ≫ ψ = ψ := by rw [← hψ]; simp
    have hd : dualHom J N e ≫ dualHom J N e = dualHom J N e := by rw [← dualHom_comp, he.idem]
    have hdc : dualHom J N e ≫ dualHom J N P.p = dualHom J N P.p ≫ dualHom J N e := by
      rw [← dualHom_comp, ← dualHom_comp, he.comm]
    refine ⟨e ≫ ψ ≫ dualHom J N e, ?_, ⟨homotopyCongr ((H₁.compRight e).compLeft e) ?_ ?_⟩,
      ⟨homotopyCongr ((H₂.compRight (dualHom J N e)).compLeft (dualHom J N e)) ?_ ?_⟩⟩
    · simp only [assoc, dualHom_comp]
      rw [he.idem_assoc, reassoc_of% hd, hdc, ← he.comm_assoc, reassoc_of% hψ]
    · simp [he.adj_assoc, he.idem]
    · rw [he.comm_assoc, he.idem]
    · simp [he.adj_assoc, he.idem_assoc]
    · rw [dualHom_comp, reassoc_of% hdc, hd, hdc]

/-- `P ≃ P.cut e` when `pe = p`. -/
def cutIsometry {e : P.C ⟶ P.C} (he : P.IsReducing e) (h : P.p ≫ e = P.p) :
    HomotopyIsometry P (P.cut he) :=
  have h' : P.φ ≫ e = P.φ := by rw [← P.φ_comp_p, assoc, h]
  .ofIso (Iso.refl _) (by simp [h]) (by simp [h'])

/-- Cuts along equal idempotents are isometric. -/
def cutCongr {e e' : P.C ⟶ P.C} (he : P.IsReducing e) (he' : P.IsReducing e') (h : e = e') :
    HomotopyIsometry (P.cut he) (P.cut he') :=
  .ofIso (Iso.refl _) (by simp [h]) (by simp [h])

/-- `P.cut (e₁ + e₂) ≃ P.cut e₁ ⊕ P.cut e₂` for orthogonal reducing idempotents. -/
def cutAddIsometry {e₁ e₂ : P.C ⟶ P.C} (h₁ : P.IsReducing e₁) (h₂ : P.IsReducing e₂)
    (h₁₂ : e₁ ≫ e₂ = 0) (h₂₁ : e₂ ≫ e₁ = 0) (b : ∀ r, BinaryBicone (P.C.X r) (P.C.X r)) :
    HomotopyIsometry (P.cut (h₁.add h₂ h₁₂ h₂₁)) ((P.cut h₁).sum (P.cut h₂) b) := by
  have h₁₂' {Z} (h : P.C ⟶ Z) : e₁ ≫ e₂ ≫ h = 0 := by rw [← assoc, h₁₂, zero_comp]
  have h₂₁' {Z} (h : P.C ⟶ Z) : e₂ ≫ e₁ ≫ h = 0 := by rw [← assoc, h₂₁, zero_comp]
  refine .ofEq (P.p ≫ e₁ ≫ sumInl b + P.p ≫ e₂ ≫ sumInr b)
    (sumFst b ≫ P.p ≫ e₁ + sumSnd b ≫ P.p ≫ e₂) ?_ ?_ ?_ ?_ ?_ <;>
    simp [add_comp, comp_add, h₁.comm_assoc, h₂.comm_assoc, h₁.idem_assoc, h₂.idem_assoc,
      h₁.idem, h₂.idem, h₁₂, h₂₁, h₁₂', h₂₁', h₁.adj_assoc, h₂.adj_assoc]

/-- The degenerate complex `(C, 0, 0)`. -/
@[simps]
def zero (C : ChainComplex V ℤ) : SymPoincare J N where
  C := C
  p := 0
  p_idem := by simp
  support _ _ := rfl
  φ := 0
  φ_kar := by simp
  symm := by simp [IsStrictSymm]
  poincare := ⟨0, by simp, ⟨.ofEq (by simp)⟩, ⟨.ofEq (by simp)⟩⟩

/-- Two complexes with `p = 0` are isometric. -/
def isometryOfPEqZero {P Q : SymPoincare J N} (hP : P.p = 0) (hQ : Q.p = 0) :
    HomotopyIsometry P Q :=
  have hφ : Q.φ = 0 := by rw [← Q.φ_comp_p, hQ, comp_zero]
  .ofEq 0 0 (by simp) (by simp) (by simp [hP]) (by simp [hQ]) (by simp [hφ])

end SymPoincare

end Cut

/-! ### The group `Lconc` -/

namespace Lconc

variable (A : InvCat) (N : ℤ)

/-- The defining relations of `Lconc A N` (design §2.3). -/
inductive Rel : FreeAbelianGroup (SymPoincare A.inv N) → Prop
  | sum (P Q : SymPoincare A.inv N) (b : ∀ r, UnitaryBicone A.inv (P.C.X r) (Q.C.X r)) :
      Rel (.of (P.sum Q fun r ↦ (b r).toBinaryBicone) - .of P - .of Q)
  | null (P : SymPoincare A.inv N) : NullCobordant P → Rel (.of P)

end Lconc

/-- The concrete L-group: strict `N`-dimensional symmetric Poincaré complexes in `Kar A` modulo
unitary sums and null-cobordisms (design §2.3; `= L^p_N(A)` for `N ≥ 0` by §2.1). -/
def Lconc (A : InvCat) (N : ℤ) : Type :=
  FreeAbelianGroup (SymPoincare A.inv N) ⧸ AddSubgroup.closure {x | Lconc.Rel A N x}

namespace Lconc

variable {A B C : InvCat} {N : ℤ}

instance : AddCommGroup (Lconc A N) :=
  inferInstanceAs (AddCommGroup (_ ⧸ AddSubgroup.closure _))

/-- The class `[P] ∈ Lconc A N` of a Poincaré complex. -/
def cls (P : SymPoincare A.inv N) : Lconc A N :=
  QuotientAddGroup.mk (s := AddSubgroup.closure {x | Rel A N x}) (.of P)

lemma cls_sum_unitary (P Q : SymPoincare A.inv N)
    (b : ∀ r, UnitaryBicone A.inv (P.C.X r) (Q.C.X r)) :
    cls (P.sum Q fun r ↦ (b r).toBinaryBicone) = cls P + cls Q := by
  have h : (QuotientAddGroup.mk (FreeAbelianGroup.of (P.sum Q fun r ↦ (b r).toBinaryBicone) -
      .of P - .of Q) : Lconc A N) = 0 :=
    (QuotientAddGroup.eq_zero_iff _).mpr (AddSubgroup.subset_closure (Rel.sum P Q b))
  rwa [QuotientAddGroup.mk_sub, QuotientAddGroup.mk_sub, sub_sub, sub_eq_zero] at h

lemma cls_eq_zero {P : SymPoincare A.inv N} (h : NullCobordant P) : cls P = 0 :=
  (QuotientAddGroup.eq_zero_iff _).mpr (AddSubgroup.subset_closure (Rel.null P h))

/-- The universal property: a function on complexes, additive on unitary sums and vanishing on
null-cobordant complexes, descends to `Lconc A N`. -/
def lift {M : Type*} [AddCommGroup M] (f : SymPoincare A.inv N → M)
    (hsum : ∀ P Q (b : ∀ r, UnitaryBicone A.inv (P.C.X r) (Q.C.X r)),
      f (P.sum Q fun r ↦ (b r).toBinaryBicone) = f P + f Q)
    (hnull : ∀ P, NullCobordant P → f P = 0) : Lconc A N →+ M :=
  QuotientAddGroup.lift _ (FreeAbelianGroup.lift f) <| (AddSubgroup.closure_le _).mpr <| by
    rintro x (⟨P, Q, b⟩ | ⟨P, hP⟩)
    · simp [hsum]
    · simp [hnull P hP]

@[simp]
lemma lift_cls {M : Type*} [AddCommGroup M] (f : SymPoincare A.inv N → M) (hsum hnull)
    (P : SymPoincare A.inv N) : lift f hsum hnull (cls P) = f P :=
  FreeAbelianGroup.lift_apply_of f P

@[ext]
lemma hom_ext {M : Type*} [AddCommGroup M] {f g : Lconc A N →+ M}
    (h : ∀ P, f (cls P) = g (cls P)) : f = g :=
  QuotientAddGroup.addMonoidHom_ext _ (FreeAbelianGroup.lift_ext _ _ h)

/-- Unitary bicones chosen in `A`. -/
def ub (P Q : SymPoincare A.inv N) (r : ℤ) : UnitaryBicone A.inv (P.C.X r) (Q.C.X r) :=
  (A.unitary _ _).some

lemma cls_neg (P : SymPoincare A.inv N) : cls P.neg = -cls P := by
  rw [eq_neg_iff_add_eq_zero, add_comm, ← cls_sum_unitary P P.neg (ub P P.neg)]
  exact cls_eq_zero (P.nullCobordant_sum_neg_self _)

/-- Homotopy-isometric complexes have equal classes ([Ran89, 3.10] via the cylinder). -/
lemma cls_eq_of_isometry {P Q : SymPoincare A.inv N} (e : P.HomotopyIsometry Q) :
    cls P = cls Q := by
  have h := cls_eq_zero (e.nullCobordant_sum_neg fun r ↦ (ub P Q.neg r).toBinaryBicone)
  rwa [cls_sum_unitary, cls_neg, add_neg_eq_zero] at h

lemma cls_eq_of_isometric {P Q : SymPoincare A.inv N} (h : P.Isometric Q) : cls P = cls Q :=
  cls_eq_of_isometry h.some

/-- Additivity along any family of (not necessarily unitary) bicones. -/
lemma cls_sum (P Q : SymPoincare A.inv N) (b : ∀ r, BinaryBicone (P.C.X r) (Q.C.X r)) :
    cls (P.sum Q b) = cls P + cls Q := by
  rw [cls_eq_of_isometry (P.sumIsometry Q b fun r ↦ (ub P Q r).toBinaryBicone), cls_sum_unitary]

lemma cls_eq_of_cobordant {P Q : SymPoincare A.inv N} (h : Cobordant P Q) : cls P = cls Q := by
  obtain ⟨b, h⟩ := h
  rwa [← sub_eq_zero, sub_eq_add_neg, ← cls_neg, ← cls_sum, cls_eq_zero]

lemma cls_cut_add (P : SymPoincare A.inv N) {e₁ e₂ : P.C ⟶ P.C} (h₁ : P.IsReducing e₁)
    (h₂ : P.IsReducing e₂) (h₁₂ : e₁ ≫ e₂ = 0) (h₂₁ : e₂ ≫ e₁ = 0) :
    cls (P.cut (h₁.add h₂ h₁₂ h₂₁)) = cls (P.cut h₁) + cls (P.cut h₂) := by
  rw [cls_eq_of_isometry (P.cutAddIsometry h₁ h₂ h₁₂ h₂₁ fun r ↦ (ub P P r).toBinaryBicone),
    cls_sum]

lemma cls_cut_eq {P : SymPoincare A.inv N} {e e' : P.C ⟶ P.C} (he : P.IsReducing e)
    (he' : P.IsReducing e') (h : e = e') : cls (P.cut he) = cls (P.cut he') :=
  cls_eq_of_isometry (P.cutCongr he he' h)

lemma cls_cut_zero (P : SymPoincare A.inv N) : cls (P.cut .zero) = 0 := by
  have h := cls_cut_add P .zero .zero (by simp) (by simp)
  rwa [cls_cut_eq _ .zero (by simp), left_eq_add] at h

lemma cls_eq_zero_of_p_eq_zero {P : SymPoincare A.inv N} (h : P.p = 0) : cls P = 0 := by
  rw [cls_eq_of_isometry (SymPoincare.isometryOfPEqZero h (by simp : (P.cut .zero).p = 0)),
    cls_cut_zero]

lemma cls_cut_of_eq (P : SymPoincare A.inv N) {e : P.C ⟶ P.C} (he : P.IsReducing e)
    (h : P.p ≫ e = P.p) : cls (P.cut he) = cls P :=
  (cls_eq_of_isometry (P.cutIsometry he h)).symm

/-- `cls` is additive along a finite family of orthogonal reducing idempotents. -/
lemma cls_cut_sum (P : SymPoincare A.inv N) {ι : Type*} (s : Finset ι) (e : ι → (P.C ⟶ P.C))
    (he : ∀ i, P.IsReducing (e i)) (horth : ∀ i j, i ≠ j → e i ≫ e j = 0)
    (hs : P.IsReducing (∑ i ∈ s, e i)) :
    cls (P.cut hs) = ∑ i ∈ s, cls (P.cut (he i)) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using cls_cut_eq hs .zero (by simp) |>.trans (cls_cut_zero P)
  | insert a s ha ih =>
    have hs' := SymPoincare.IsReducing.sum s he horth
    have h₁ : e a ≫ ∑ i ∈ s, e i = 0 := by
      rw [comp_sum]; exact Finset.sum_eq_zero fun i hi ↦ horth a i (by rintro rfl; exact ha hi)
    have h₂ : (∑ i ∈ s, e i) ≫ e a = 0 := by
      rw [sum_comp]; exact Finset.sum_eq_zero fun i hi ↦ horth i a (by rintro rfl; exact ha hi)
    calc cls (P.cut hs) = cls (P.cut ((he a).add hs' h₁ h₂)) :=
          cls_cut_eq _ _ (Finset.sum_insert ha)
      _ = _ := by rw [cls_cut_add P (he a) hs' h₁ h₂, ih hs', Finset.sum_insert ha]

/-- `Lconc A N = 0` for `N < 0`: complexes are concentrated in degrees `[0, N]`. -/
lemma cls_eq_zero_of_neg (hN : N < 0) (P : SymPoincare A.inv N) : cls P = 0 :=
  cls_eq_zero_of_p_eq_zero (by ext r; exact P.support r (by omega))

open ZeroObject in
/-- Every element of `Lconc A N` is the class of a single complex. -/
lemma cls_surjective : Function.Surjective (cls : SymPoincare A.inv N → Lconc A N) := by
  intro x
  obtain ⟨x, rfl⟩ := QuotientAddGroup.mk_surjective x
  induction x using FreeAbelianGroup.induction_on with
  | zero => exact ⟨.zero 0, cls_eq_zero_of_p_eq_zero rfl⟩
  | of P => exact ⟨P, rfl⟩
  | neg P _ => exact ⟨P.neg, cls_neg P⟩
  | add x y hx hy =>
    obtain ⟨P, hP⟩ := hx
    obtain ⟨Q, hQ⟩ := hy
    exact ⟨P.sum Q fun r ↦ (ub P Q r).toBinaryBicone, by
      rw [cls_sum, hP, hQ]; rfl⟩

end Lconc

/-! ### Functoriality -/

section Retract

variable {A B : InvCat} {N : ℤ} {Φ Ψ : A ⟶ B} (ι : Ψ.F ⟶ Φ.F)

/-- The adjoint `ι^* : Φ ⟶ Ψ` of a natural transformation of duality-preserving functors. -/
@[simps]
def adjNatTrans : Φ.F ⟶ Ψ.F where
  app X := B.inv.star (ι.app X)
  naturality X Y f := by
    have := congrArg B.inv.star (ι.naturality (A.inv.star f))
    simpa [B.inv.star_comp, Φ.map_star, Ψ.map_star, B.inv.star_star] using this.symm

@[reassoc (attr := simp)]
lemma map_comp_star_app {X Y : A} (f : X ⟶ Y) :
    Φ.F.map f ≫ B.inv.star (ι.app Y) = B.inv.star (ι.app X) ≫ Ψ.F.map f :=
  (adjNatTrans ι).naturality f

/-- The chain map `ι_C : Ψ(C) ⟶ Φ(C)`. -/
abbrev natChain {Φ Ψ : A ⟶ B} (ι : Ψ.F ⟶ Φ.F) (C : ChainComplex A ℤ) :
    (Ψ : InvFunctor A.inv B.inv).mapC C ⟶ (Φ : InvFunctor A.inv B.inv).mapC C :=
  (NatTrans.mapHomologicalComplex ι _).app C

variable (P : SymPoincare A.inv N)

/-- The idempotent `ι^* ι` of `Φ(C)` for an isometric embedding `ι : Ψ ⟶ Φ`. -/
abbrev retractIdem : (P.map Φ).C ⟶ (P.map Φ).C := natChain (adjNatTrans ι ≫ ι) P.C

omit ι in
@[reassoc (attr := simp)]
lemma map_p_f_idem (F : A ⥤ B) (r : ℤ) :
    F.map (P.p.f r) ≫ F.map (P.p.f r) = F.map (P.p.f r) := by
  rw [← F.map_comp, ← comp_f, P.p_idem]

variable {ι} (hι : ∀ X, ι.app X ≫ B.inv.star (ι.app X) = 𝟙 _)
include hι

lemma isReducing_retractIdem : (P.map Φ).IsReducing (retractIdem ι P) where
  idem := by ext; simp [reassoc_of% (hι _)]
  comm := by ext; simp
  adj := by ext; simp [B.inv.star_comp, B.inv.star_star]

/-- `Φ(P)` cut down by `ι^* ι` is isometric to `Ψ(P)`. -/
def retractIsometry :
    ((P.map Φ).cut (isReducing_retractIdem P hι)).HomotopyIsometry (P.map Ψ) := by
  have hk (r : ℤ) : Ψ.F.map (A.inv.star (P.p.f (N - r))) ≫ Ψ.F.map (P.φ.f r) ≫
      Ψ.F.map (P.p.f r) = Ψ.F.map (P.φ.f r) := by
    have := congrArg (fun φ ↦ Ψ.F.map (φ.f r)) P.φ_kar
    simpa only [comp_f, dualHom_f, Functor.map_comp] using this
  have hι₂ (X : A) {Z : B} (h : Ψ.F.obj X ⟶ Z) : ι.app X ≫ B.inv.star (ι.app X) ≫ h = h := by
    rw [← assoc, hι, id_comp]
  refine .ofEq ((P.map Φ).p ≫ natChain (adjNatTrans ι) P.C) ((P.map Ψ).p ≫ natChain ι P.C)
    ?_ ?_ ?_ ?_ ?_ <;> ext <;> simp [B.inv.star_star, ← Ψ.map_star, hk, hι₂]

end Retract

namespace Lconc

variable {A B C : InvCat} {N : ℤ}

/-- Functoriality of `Lconc` along duality-preserving functors. -/
def map (Φ : A ⟶ B) : Lconc A N →+ Lconc B N :=
  lift (fun P ↦ cls (P.map Φ))
    (fun P Q b ↦ by rw [cls_eq_of_isometry (SymPoincare.mapSum Φ P Q _), cls_sum])
    (fun _ hP ↦ cls_eq_zero (hP.map Φ))

@[simp]
lemma map_cls (Φ : A ⟶ B) (P : SymPoincare A.inv N) : map Φ (cls P) = cls (P.map Φ) :=
  lift_cls _ _ _ P

@[simp]
lemma map_id : map (𝟙 A) = AddMonoidHom.id (Lconc A N) := by
  ext P; simp; rfl

lemma map_comp (Φ : A ⟶ B) (Ψ : B ⟶ C) :
    map (Φ ≫ Ψ) = (map Ψ).comp (map Φ : Lconc A N →+ _) := by
  ext P; simp; rfl

lemma map_retract {Φ Ψ : A ⟶ B} (ι : Ψ.F ⟶ Φ.F)
    (hι : ∀ X, ι.app X ≫ B.inv.star (ι.app X) = 𝟙 _) (P : SymPoincare A.inv N) :
    cls (P.map Ψ) = cls ((P.map Φ).cut (isReducing_retractIdem P hι)) :=
  (cls_eq_of_isometry (retractIsometry P hι)).symm

/-- Unitarily isomorphic functors induce the same map (design U8). -/
theorem map_eq_of_unitaryIso {Φ Ψ : A ⟶ B} (e : InvCat.UnitaryIso Φ Ψ) :
    (map Φ : Lconc A N →+ _) = map Ψ := by
  ext P
  rw [map_cls, map_cls, map_retract e.iso.inv (fun X ↦ by simp [e.star_inv]), cls_cut_of_eq]
  ext; simp [e.star_inv]

lemma hom_sum_f {ι : Type*} {X Y : ChainComplex B ℤ} (s : Finset ι) (f : ι → (X ⟶ Y)) (r : ℤ) :
    (∑ i ∈ s, f i).f r = ∑ i ∈ s, (f i).f r :=
  map_sum (HomologicalComplex.eval B _ r).mapAddHom f s

/-- Additivity along finite unitary sums of functors (design U8). -/
theorem map_finSum {ι : Type*} [Fintype ι] {Φ : ι → (A ⟶ B)} {S : A ⟶ B}
    (h : InvCat.IsFinSum Φ S) : (map S : Lconc A N →+ _) = ∑ i, map (Φ i) := by
  classical
  ext P
  simp only [map_cls, AddMonoidHom.finsetSum_apply]
  have he i := isReducing_retractIdem P (h.inc_star_self i)
  have horth : ∀ i j, i ≠ j → retractIdem (h.inc i) P ≫ retractIdem (h.inc j) P = 0 :=
    fun i j hij ↦ by ext; simp [reassoc_of% (h.inc_star_ne i j hij)]
  have htot : ∑ i, retractIdem (h.inc i) P = 𝟙 _ := by ext; simp [hom_sum_f, h.total]
  rw [← cls_cut_of_eq (P.map S) (SymPoincare.IsReducing.sum Finset.univ he horth)
    (by rw [htot, comp_id]), cls_cut_sum _ _ _ he horth]
  exact Finset.sum_congr rfl fun i _ ↦ (map_retract _ (h.inc_star_self i) P).symm

/-- A functor all of whose values are zero objects induces the zero map. -/
lemma map_eq_zero_of_isZero {Φ : A ⟶ B} (h : ∀ X, IsZero (Φ.F.obj X)) :
    (map Φ : Lconc A N →+ _) = 0 := by
  ext P
  exact cls_eq_zero_of_p_eq_zero (by ext r; exact (h _).eq_of_src _ _)

end Lconc

/-! ### Products and finite-support sums -/

namespace InvCat

variable {ι : Type} (A : ι → InvCat)

instance : Preadditive (∀ i, A i) where
  homGroup X Y := inferInstanceAs (AddCommGroup (∀ i, X i ⟶ Y i))
  add_comp _ _ _ _ _ _ := funext fun _ ↦ add_comp _ _ _ _ _ _
  comp_add _ _ _ _ _ _ := funext fun _ ↦ comp_add _ _ _ _ _ _

instance : Linear ℚ (∀ i, A i) where
  homModule X Y := inferInstanceAs (Module ℚ (∀ i, X i ⟶ Y i))
  smul_comp _ _ _ _ _ _ := funext fun _ ↦ Linear.smul_comp _ _ _ _ _ _
  comp_smul _ _ _ _ _ _ := funext fun _ ↦ Linear.comp_smul _ _ _ _ _ _

lemma pi_isZero {X : ∀ i, A i} (h : ∀ i, IsZero (X i)) : IsZero X :=
  (IsZero.iff_id_eq_zero _).mpr (funext fun i ↦ (h i).eq_of_src _ _)

open ZeroObject in
instance : HasZeroObject (∀ i, A i) := ⟨⟨fun _ ↦ 0, pi_isZero A fun _ ↦ isZero_zero _⟩⟩

variable {A} in
/-- The componentwise bicone. -/
@[simps]
def piBicone {X Y : ∀ i, A i} (b : ∀ i, BinaryBicone (X i) (Y i)) : BinaryBicone X Y where
  pt i := (b i).pt
  fst i := (b i).fst
  snd i := (b i).snd
  inl i := (b i).inl
  inr i := (b i).inr
  inl_fst := funext fun i ↦ (b i).inl_fst
  inl_snd := funext fun i ↦ (b i).inl_snd
  inr_fst := funext fun i ↦ (b i).inr_fst
  inr_snd := funext fun i ↦ (b i).inr_snd

variable {A} in
/-- The componentwise bicone of unitary bicones is a bilimit. -/
def piBiconeIsBilimit {X Y : ∀ i, A i} (b : ∀ i, UnitaryBicone (A i).inv (X i) (Y i)) :
    (piBicone fun i ↦ (b i).toBinaryBicone).IsBilimit :=
  isBinaryBilimitOfTotal _ (funext fun i ↦ IsBilimit.binary_total (b i).isBilimit)

instance : HasBinaryBiproducts (∀ i, A i) :=
  ⟨fun X Y ↦ HasBinaryBiproduct.mk ⟨_, piBiconeIsBilimit fun i ↦ ((A i).unitary (X i) (Y i)).some⟩⟩

instance : HasFiniteBiproducts (∀ i, A i) := hasFiniteBiproducts_of_binary

/-- The componentwise involution. -/
@[simps]
def piInvolution : StrictInvolution (∀ i, A i) where
  star f i := (A i).inv.star (f i)
  star_comp f g := funext fun i ↦ (A i).inv.star_comp (f i) (g i)
  star_id X := funext fun i ↦ (A i).inv.star_id (X i)
  star_add f g := funext fun i ↦ (A i).inv.star_add (f i) (g i)
  star_star f := funext fun i ↦ (A i).inv.star_star (f i)

/-- The product `∏ᵢ Aᵢ` of `InvCat`s. -/
def pi : InvCat where
  carrier := ∀ i, A i
  inv := piInvolution A
  unitary X Y :=
    ⟨{ toBinaryBicone := piBicone fun i ↦ ((A i).unitary (X i) (Y i)).some.toBinaryBicone
       isBilimit := piBiconeIsBilimit fun i ↦ ((A i).unitary (X i) (Y i)).some
       star_inl := funext fun i ↦ ((A i).unitary (X i) (Y i)).some.star_inl
       star_inr := funext fun i ↦ ((A i).unitary (X i) (Y i)).some.star_inr }⟩

/-- The coordinate projection `∏ⱼ Aⱼ → Aᵢ`. -/
@[simps]
def eval (i : ι) : pi A ⟶ A i where
  F := Pi.eval (fun i ↦ (A i).carrier) i
  additive := ⟨rfl⟩
  map_star _ := rfl

variable {A}

@[simp] lemma pi_add_apply {X Y : pi A} (f g : X ⟶ Y) (i : ι) : (f + g) i = f i + g i := rfl

@[simp] lemma pi_zero_apply {X Y : pi A} (i : ι) : (0 : X ⟶ Y) i = 0 := rfl

@[simp] lemma pi_sum_apply {X Y : pi A} {κ : Type*} (s : Finset κ) (f : κ → (X ⟶ Y)) (i : ι) :
    (∑ k ∈ s, f k) i = ∑ k ∈ s, f k i :=
  map_sum (⟨⟨fun g : X ⟶ Y ↦ g i, rfl⟩, fun _ _ ↦ rfl⟩ : (X ⟶ Y) →+ (X i ⟶ Y i)) f s

@[simp] lemma pi_units_smul_apply {X Y : pi A} (u : ℤˣ) (f : X ⟶ Y) (i : ι) :
    (u • f) i = u • f i := rfl

@[simp] lemma pi_comp_apply {X Y Z : pi A} (f : X ⟶ Y) (g : Y ⟶ Z) (i : ι) :
    (f ≫ g) i = f i ≫ g i := rfl

@[simp] lemma pi_id_apply (X : pi A) (i : ι) : (𝟙 X : X ⟶ X) i = 𝟙 (X i) := rfl

@[simp] lemma pi_star_apply {X Y : pi A} (f : X ⟶ Y) (i : ι) :
    (pi A).inv.star f i = (A i).inv.star (f i) := rfl

@[simp] lemma pi_eqToHom_apply {X Y : pi A} (h : X = Y) (i : ι) :
    (eqToHom h : X ⟶ Y) i = eqToHom (congrFun h i) := by
  subst h; rfl

/-- The componentwise chain complex. -/
@[simps]
def piComplex (C : ∀ i, ChainComplex (A i) ℤ) : ChainComplex (pi A) ℤ where
  X r i := (C i).X r
  d r r' i := (C i).d r r'
  shape r r' h := funext fun i ↦ (C i).shape r r' h
  d_comp_d' r r' r'' _ _ := funext fun i ↦ (C i).d_comp_d r r' r''

variable {N : ℤ} {C D : ∀ i, ChainComplex (A i) ℤ}

/-- The componentwise chain map. -/
@[simps]
def piHom (f : ∀ i, C i ⟶ D i) : piComplex C ⟶ piComplex D where
  f r i := (f i).f r
  comm' r r' _ := funext fun i ↦ (f i).comm r r'

/-- The componentwise chain map out of a dual. -/
@[simps]
def piDualHom (f : ∀ i, dualComplex (A i).inv N (C i) ⟶ D i) :
    dualComplex (pi A).inv N (piComplex C) ⟶ piComplex D where
  f r i := (f i).f r
  comm' r r' _ := funext fun i ↦ (f i).comm r r'

/-- The componentwise chain map into a dual. -/
@[simps]
def piToDual (f : ∀ i, C i ⟶ dualComplex (A i).inv N (D i)) :
    piComplex C ⟶ dualComplex (pi A).inv N (piComplex D) where
  f r i := (f i).f r
  comm' r r' _ := funext fun i ↦ (f i).comm r r'

/-- Componentwise homotopies. -/
def piHomotopy {X Y : ChainComplex (pi A) ℤ} {f g : X ⟶ Y}
    (H : ∀ i, Homotopy ((eval A i).mapH f) ((eval A i).mapH g)) : Homotopy f g where
  hom r r' i := (H i).hom r r'
  zero r r' h := funext fun i ↦ (H i).zero r r' h
  comm r := funext fun i ↦ (H i).comm r

end InvCat

namespace SymPoincare

open InvCat

variable {ι : Type} {A : ι → InvCat} {N : ℤ}

/-- The componentwise Poincaré complex in `∏ᵢ Aᵢ`. -/
@[simps]
def pi (P : ∀ i, SymPoincare (A i).inv N) : SymPoincare (InvCat.pi A).inv N where
  C := piComplex fun i ↦ (P i).C
  p := piHom fun i ↦ (P i).p
  p_idem := Hom.ext (funext fun r ↦ funext fun i ↦ congr_hom (P i).p_idem r)
  support r hr := funext fun i ↦ (P i).support r hr
  φ := piDualHom fun i ↦ (P i).φ
  φ_kar := Hom.ext (funext fun r ↦ funext fun i ↦ congr_hom (P i).φ_kar r)
  symm := Hom.ext (funext fun r ↦ funext fun i ↦ by
    have := congr_hom (P i).symm r
    rw [transposeHom_f] at this ⊢
    simp
    exact this)
  poincare := by
    choose ψ hψ H₁ H₂ using fun i ↦ (P i).poincare
    exact ⟨piToDual ψ, Hom.ext (funext fun r ↦ funext fun i ↦ congr_hom (hψ i) r),
      ⟨piHomotopy fun i ↦ (H₁ i).some⟩, ⟨piHomotopy fun i ↦ (H₂ i).some⟩⟩

lemma pi_map_eval (P : ∀ i, SymPoincare (A i).inv N) (i : ι) :
    (SymPoincare.pi P).map (eval A i) = P i := rfl

end SymPoincare

namespace InvCat

variable {ι : Type} [DecidableEq ι] (A : ι → InvCat)

open ZeroObject

/-- The object of `∏ⱼ Aⱼ` concentrated in index `i`. -/
def singleObj (i : ι) (X : A i) : pi A := Function.update (fun j ↦ (0 : A j)) i X

lemma singleObj_isZero {i j : ι} (h : j ≠ i) (X : A i) : IsZero (singleObj A i X j) := by
  rw [singleObj, Function.update_of_ne h]; exact isZero_zero _

lemma singleObj_self (i : ι) (X : A i) : singleObj A i X i = X := Function.update_self ..

/-- The morphism of `∏ⱼ Aⱼ` concentrated in index `i`. -/
def singleMap (i : ι) {X Y : A i} (f : X ⟶ Y) : singleObj A i X ⟶ singleObj A i Y :=
  Function.update (β := fun j ↦ singleObj A i X j ⟶ singleObj A i Y j) (fun _ ↦ 0) i
    (eqToHom (singleObj_self A i X) ≫ f ≫ eqToHom (singleObj_self A i Y).symm)

lemma singleMap_self (i : ι) {X Y : A i} (f : X ⟶ Y) : singleMap A i f i =
    eqToHom (singleObj_self A i X) ≫ f ≫ eqToHom (singleObj_self A i Y).symm :=
  Function.update_self ..

lemma singleMap_ne {i j : ι} (h : j ≠ i) {X Y : A i} (f : X ⟶ Y) : singleMap A i f j = 0 :=
  Function.update_of_ne h ..

/-- The inclusion `Aᵢ → ∏ⱼ Aⱼ` of the `i`-th factor. -/
def single (i : ι) : A i ⟶ pi A where
  F :=
    { obj := singleObj A i
      map := singleMap A i
      map_id X := funext fun j ↦ by
        by_cases h : j = i
        · subst h; simp [singleMap_self]
        · exact (singleObj_isZero A h X).eq_of_src _ _
      map_comp f g := funext fun j ↦ by
        by_cases h : j = i
        · subst h; simp [singleMap_self]
        · simp [singleMap_ne A h] }
  additive := ⟨fun {X Y f g} ↦ funext fun j ↦ by
    by_cases h : j = i
    · subst h; simp [singleMap_self]
    · simp [singleMap_ne A h]⟩
  map_star f := funext fun j ↦ by
    by_cases h : j = i
    · subst h; simp [singleMap_self, (A j).inv.star_comp, star_eqToHom]
    · simp [singleMap_ne A h]

@[simp] lemma single_obj (i : ι) (X : A i) : (single A i).F.obj X = singleObj A i X := rfl

@[simp] lemma single_map (i : ι) {X Y : A i} (f : X ⟶ Y) :
    (single A i).F.map f = singleMap A i f := rfl

/-- The inclusion `ιᵢ : (Xᵢ at i) ⟶ X`. -/
def singleInc (i : ι) : (eval A i ≫ single A i).F ⟶ (𝟙 (pi A) : pi A ⟶ pi A).F where
  app X := Function.update (β := fun j ↦ singleObj A i (X i) j ⟶ X j) (fun _ ↦ 0) i
    (eqToHom (singleObj_self A i (X i)))
  naturality X Y f := funext fun j ↦ by
    erw [pi_comp_apply, pi_comp_apply]
    by_cases h : j = i
    · subst h; simp [singleMap_self]
      erw [Category.assoc, Category.assoc, eqToHom_trans, eqToHom_refl, Category.comp_id]
      try rfl
    · simp [Function.update_of_ne h]
      erw [comp_zero, zero_comp]

lemma singleInc_self (i : ι) (X : pi A) :
    (singleInc A i).app X i = eqToHom (singleObj_self A i (X i)) := by
  dsimp only [singleInc]
  exact Function.update_self ..

lemma singleInc_ne {i j : ι} (h : j ≠ i) (X : pi A) : (singleInc A i).app X j = 0 := by
  dsimp only [singleInc]
  exact Function.update_of_ne h ..

lemma singleInc_star_self (i : ι) (X : pi A) :
    (singleInc A i).app X ≫ (pi A).inv.star ((singleInc A i).app X) = 𝟙 _ := funext fun j ↦ by
  erw [pi_comp_apply, pi_star_apply]
  by_cases h : j = i
  · subst h; simp [singleInc_self, star_eqToHom]
    erw [star_eqToHom, eqToHom_trans, eqToHom_refl]
  · exact (singleObj_isZero A h _).eq_of_src _ _

lemma singleInc_star_ne {i j : ι} (hij : i ≠ j) (X : pi A) :
    (singleInc A i).app X ≫ (pi A).inv.star ((singleInc A j).app X) = 0 := funext fun k ↦ by
  erw [pi_comp_apply, pi_star_apply]
  by_cases h : k = i
  · subst h; simp [singleInc_ne A hij]
    erw [StrictInvolution.star_zero, comp_zero]; rfl
  · simp [singleInc_ne A h]
    erw [zero_comp]; rfl

lemma sum_singleInc_apply (S : Finset ι) (X : pi A) (k : ι) :
    (∑ i ∈ S, (pi A).inv.star ((singleInc A i).app X) ≫ (singleInc A i).app X) k =
      if k ∈ S then 𝟙 _ else 0 := by
  rw [pi_sum_apply]
  split_ifs with hk
  · rw [Finset.sum_eq_single k (fun i _ hi ↦ by
      erw [pi_comp_apply, pi_star_apply]; simp [singleInc_ne A (Ne.symm hi)]
      erw [comp_zero]; rfl) (by simp [hk])]
    erw [pi_comp_apply, pi_star_apply]
    simp [singleInc_self, star_eqToHom]
    erw [star_eqToHom, eqToHom_trans, eqToHom_refl]
  · exact Finset.sum_eq_zero fun i hi ↦ by
      erw [pi_comp_apply, pi_star_apply]
      simp [singleInc_ne A (show k ≠ i by rintro rfl; exact hk hi)]
      erw [comp_zero]; rfl

/-- `𝟙 = ∑ᵢ ιᵢ πᵢ` on `∏ᵢ Aᵢ` for a finite index set. -/
def isFinSum_single [Fintype ι] : IsFinSum (fun i ↦ eval A i ≫ single A i) (𝟙 (pi A)) where
  inc := singleInc A
  inc_star_self := singleInc_star_self A
  inc_star_ne _ _ := singleInc_star_ne A
  total X := funext fun j ↦ by rw [sum_singleInc_apply, ite_eq_left (Finset.mem_univ j)]; rfl

end InvCat

namespace Lconc

open InvCat

variable {ι : Type} {A : ι → InvCat} {N : ℤ}

/-- The comparison `Lconc (∏ᵢ Aᵢ) → ∏ᵢ Lconc Aᵢ` given by the coordinate projections. -/
def piComparison : Lconc (pi A) N →+ ∀ i, Lconc (A i) N :=
  AddMonoidHom.pi fun i ↦ map (eval A i)

@[simp]
lemma piComparison_apply (x : Lconc (pi A) N) (i : ι) : piComparison x i = map (eval A i) x := rfl

theorem piComparison_surjective : Function.Surjective (piComparison (A := A) (N := N)) := by
  intro x
  choose P hP using fun i ↦ cls_surjective (x i)
  exact ⟨cls (SymPoincare.pi P), funext fun i ↦ by
    rw [piComparison_apply, map_cls, SymPoincare.pi_map_eval, hP]⟩

theorem piComparison_injective [Finite ι] :
    Function.Injective (piComparison (A := A) (N := N)) := by
  classical
  have := Fintype.ofFinite ι
  refine (injective_iff_map_eq_zero _).mpr fun x hx ↦ ?_
  have h := congrArg (· x) (map_finSum (N := N) (isFinSum_single A))
  simp only [map_id, AddMonoidHom.id_apply, AddMonoidHom.finsetSum_apply, map_comp,
    AddMonoidHom.comp_apply] at h
  rw [h]
  exact Finset.sum_eq_zero fun i _ ↦ by
    rw [← piComparison_apply, hx, Pi.zero_apply, AddMonoidHom.map_zero]

/-- For finitely many factors, `Lconc (∏ᵢ Aᵢ) ≅ ∏ᵢ Lconc Aᵢ`. -/
def piComparisonEquiv [Finite ι] : Lconc (pi A) N ≃+ ∀ i, Lconc (A i) N :=
  AddEquiv.ofBijective piComparison ⟨piComparison_injective, piComparison_surjective⟩

end Lconc

namespace InvCat

variable {ι : Type} (A : ι → InvCat)

open ZeroObject

/-- Objects of `∏ᵢ Aᵢ` with finitely many nonzero components. -/
def finSuppProp : ObjectProperty (pi A) := fun X ↦ {i | ¬IsZero (X i)}.Finite

instance : IsAdditiveSub (finSuppProp A) where
  of_iso e h := h.subset fun i hi hz ↦
    hi (hz.of_iso ⟨e.inv i, e.hom i, congrFun e.inv_hom_id i, congrFun e.hom_inv_id i⟩)
  exists_zero := ⟨fun _ ↦ 0, pi_isZero A fun _ ↦ isZero_zero _,
    Set.finite_empty.subset fun _ hi ↦ hi (isZero_zero _)⟩
  biprod_mem b hb hX hY := (hX.union hY).subset fun i hi ↦ by
    by_contra h
    simp only [Set.mem_union, Set.mem_ofPred_eq, not_or, not_not] at h
    refine hi ((IsZero.iff_id_eq_zero _).mpr ?_)
    have := congrFun (IsBilimit.binary_total hb) i
    rw [← pi_id_apply, ← this, pi_add_apply, pi_comp_apply, pi_comp_apply,
      h.1.eq_of_src (b.inl i) 0, h.2.eq_of_src (b.inr i) 0, comp_zero, comp_zero, add_zero]

/-- The finite-support sum `⊕ᵢ Aᵢ ⊂ ∏ᵢ Aᵢ`. -/
abbrev finSupp : InvCat := (pi A).sub (finSuppProp A)

/-- The coordinate projection `⊕ⱼ Aⱼ → Aᵢ`. -/
abbrev evalFS (i : ι) : finSupp A ⟶ A i := (pi A).subIncl _ ≫ eval A i

variable [DecidableEq ι]

/-- The inclusion `Aᵢ → ⊕ⱼ Aⱼ`. -/
def singleFS (i : ι) : A i ⟶ finSupp A where
  F := (finSuppProp A).lift (single A i).F fun X ↦ (Set.finite_singleton i).subset
    fun _ hj ↦ by_contra fun h ↦ hj (singleObj_isZero A h X)
  additive := { map_add := ObjectProperty.hom_ext _ (single A i).F.map_add }
  map_star f := ObjectProperty.hom_ext _ ((single A i).map_star f)

/-- The inclusion `ιᵢ` on `⊕ⱼ Aⱼ`. -/
def singleIncFS (i : ι) :
    (evalFS A i ≫ singleFS A i).F ⟶ (𝟙 (finSupp A) : finSupp A ⟶ _).F where
  app X := ObjectProperty.homMk ((singleInc A i).app X.obj)
  naturality _ _ f := ObjectProperty.hom_ext _ ((singleInc A i).naturality f.hom)

end InvCat

namespace Lconc

open InvCat

variable {ι : Type} {A : ι → InvCat} {N : ℤ}

/-- The comparison `Lconc (⊕ᵢ Aᵢ) → ∏ᵢ Lconc Aᵢ` given by the coordinate projections. -/
def finSuppComparison : Lconc (finSupp A) N →+ ∀ i, Lconc (A i) N :=
  AddMonoidHom.pi fun i ↦ map (evalFS A i)

@[simp]
lemma finSuppComparison_apply (x : Lconc (finSupp A) N) (i : ι) :
    finSuppComparison x i = map (evalFS A i) x := rfl

/-- A complex in `⊕ᵢ Aᵢ` is supported in finitely many indices. -/
lemma exists_support (P : SymPoincare (finSupp A).inv N) :
    ∃ S : Finset ι, ∀ r j, j ∉ S → (P.p.f r).hom j = 0 := by
  classical
  refine ⟨(Finset.Icc 0 N).biUnion fun r ↦ (P.C.X r).property.toFinset, fun r j hj ↦ ?_⟩
  by_cases hr : r ∈ Finset.Icc 0 N
  · refine IsZero.eq_of_src (by_contra fun h ↦ hj (Finset.mem_biUnion.mpr ⟨r, hr, ?_⟩)) _ _
    exact (Set.Finite.mem_toFinset _).mpr h
  · rw [P.support r (by simp at hr; omega)]; rfl

lemma finSuppComparison_cls_eq_zero (P : SymPoincare (finSupp A).inv N) {S : Finset ι}
    (hS : ∀ r j, j ∉ S → (P.p.f r).hom j = 0) {j : ι} (hj : j ∉ S) :
    finSuppComparison (cls P) j = 0 := by
  rw [finSuppComparison_apply, map_cls]
  exact cls_eq_zero_of_p_eq_zero (by ext r; exact hS r j hj)

/-- The image of `Lconc (⊕ᵢ Aᵢ)` consists of finitely supported families. -/
theorem finite_support_finSuppComparison (x : Lconc (finSupp A) N) :
    {i | finSuppComparison x i ≠ 0}.Finite := by
  obtain ⟨P, rfl⟩ := cls_surjective x
  obtain ⟨S, hS⟩ := exists_support P
  exact S.finite_toSet.subset fun j hj ↦
    by_contra fun h ↦ hj (finSuppComparison_cls_eq_zero P hS h)

lemma cls_eq_sum_single [DecidableEq ι] (P : SymPoincare (finSupp A).inv N) {S : Finset ι}
    (hS : ∀ r j, j ∉ S → (P.p.f r).hom j = 0) :
    cls P = ∑ i ∈ S, map (singleFS A i) (finSuppComparison (cls P) i) := by
  have hι i X :
      (singleIncFS A i).app X ≫ (finSupp A).inv.star ((singleIncFS A i).app X) = 𝟙 _ :=
    ObjectProperty.hom_ext _ (singleInc_star_self A i X.obj)
  have hne i j (hij : i ≠ j) X :
      (singleIncFS A i).app X ≫ (finSupp A).inv.star ((singleIncFS A j).app X) = 0 :=
    ObjectProperty.hom_ext _ (singleInc_star_ne A hij X.obj)
  have he i := isReducing_retractIdem P (hι i)
  have horth : ∀ i j, i ≠ j → retractIdem (singleIncFS A i) P ≫
      retractIdem (singleIncFS A j) P = 0 :=
    fun i j hij ↦ by
      ext r : 1
      change (adjNatTrans (singleIncFS A i) ≫ singleIncFS A i).app (P.C.X r) ≫
        (adjNatTrans (singleIncFS A j) ≫ singleIncFS A j).app (P.C.X r) = 0
      erw [NatTrans.comp_app, NatTrans.comp_app]
      simp only [Category.assoc]
      erw [reassoc_of% (hne i j hij), zero_comp, comp_zero]
  have hsum : (P.map (𝟙 (finSupp A) : finSupp A ⟶ _)).p ≫
      ∑ i ∈ S, retractIdem (singleIncFS A i) P = (P.map (𝟙 (finSupp A) : finSupp A ⟶ _)).p := by
    ext r : 1
    refine ObjectProperty.hom_ext _ (funext fun k ↦ ?_)
    have key : (∑ i ∈ S, (retractIdem (singleIncFS A i) P).f r).hom =
        ∑ i ∈ S, (pi A).inv.star ((singleInc A i).app (P.C.X r).obj) ≫
          (singleInc A i).app (P.C.X r).obj := by
      exact Functor.map_sum (ObjectProperty.ι _) _ S
    rw [comp_f, hom_sum_f]
    change ((P.p.f r).hom ≫ (∑ i ∈ S, (retractIdem (singleIncFS A i) P).f r).hom) k =
      (P.p.f r).hom k
    rw [key]
    erw [pi_comp_apply, sum_singleInc_apply]
    split_ifs with hk
    · exact comp_id _
    · erw [comp_zero, hS r k hk]
      rfl
  change cls (P.map (𝟙 (finSupp A) : finSupp A ⟶ _)) = _
  rw [← cls_cut_of_eq _ (SymPoincare.IsReducing.sum S he horth) hsum,
    cls_cut_sum _ _ _ he horth]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [finSuppComparison_apply, map_cls, map_cls, ← map_retract _ (hι i) P]
  rfl

/-- `Lconc (⊕ᵢ Aᵢ) → ∏ᵢ Lconc Aᵢ` is injective. -/
theorem finSuppComparison_injective :
    Function.Injective (finSuppComparison (A := A) (N := N)) := by
  classical
  refine (injective_iff_map_eq_zero _).mpr fun x hx ↦ ?_
  obtain ⟨P, rfl⟩ := cls_surjective x
  obtain ⟨S, hS⟩ := exists_support P
  rw [cls_eq_sum_single P hS, hx]
  simp

end Lconc

end

end HSFormal.LTheory
