import Mathlib
import TauCeti.RepresentationTheory.Compact.RepresentativeDensity
import TauCeti.RepresentationTheory.Compact.UnitaryModel

/-!
# [Tao11, Lemma 7], part 1: circle characters of a compact monothetic group

Let `B` be a compact Hausdorff commutative group which is *monothetic*: the cyclic subgroup
generated by some `g : B` is dense. Then the continuous characters `B →* Circle` separate the points
of `B` (`HSFormal.Lemma7.exists_char_ne_one`).

Proof. By Peter–Weyl (TauCeti: `TauCeti.exists_isRepresentative_apply_ne`, made unitary by
`TauCeti.isRepresentative_iff_exists_isUnitary`) there is a finite-dimensional continuous unitary
representation `π` with `π b ≠ 1`. Let `W = ker (π b - 1)`; since `B` is commutative and `π` is
unitary, `W` and `Wᗮ ≠ 0` are `π`-invariant. Pick an eigenvector `v ∈ Wᗮ` of `π g`. The set of
`c` for which `v` is an eigenvector of `π c` is a closed subgroup containing `g`, hence all of `B`;
the eigenvalue `χ c = ⟪v, π c v⟫ / ⟪v, v⟫` is a continuous unitary character, and `χ b ≠ 1`
because `v ∉ W`.
-/

open scoped InnerProductSpace
open Topology

namespace HSFormal.Lemma7

variable {B : Type*} [CommGroup B] [TopologicalSpace B] [IsTopologicalGroup B] [CompactSpace B]
  [T2Space B]

/-- Peter–Weyl, unitary form: a nontrivial element acts nontrivially in some finite-dimensional
continuous unitary representation. -/
theorem exists_unitary_rep_ne (b : B) (hb : b ≠ 1) :
    ∃ (n : ℕ) (π : ContRepresentation ℂ B (EuclideanSpace ℂ (Fin n))), Continuous π ∧
      TauCeti.ContRepresentation.IsUnitary π ∧ π b ≠ 1 := by
  let _ : MeasurableSpace B := borel B
  have _ : BorelSpace B := ⟨rfl⟩
  obtain ⟨f, hf, hne⟩ := TauCeti.exists_isRepresentative_apply_ne (𝕜 := ℂ) b 1 hb
  obtain ⟨n, π, hπ, hU, v, w, rfl⟩ := TauCeti.isRepresentative_iff_exists_isUnitary.1 hf
  refine ⟨n, π, hπ, hU, fun h => hne ?_⟩
  simp [TauCeti.ContRepresentation.matrixCoeff_apply, h]

/-- **Circle characters separate the points of a compact Hausdorff monothetic group.** -/
theorem exists_char_ne_one (g : B) (hg : Dense (Subgroup.zpowers g : Set B)) (b : B)
    (hb : b ≠ 1) : ∃ χ : B →* Circle, Continuous χ ∧ χ b ≠ 1 := by
  obtain ⟨n, π, hπ, hU, hπb⟩ := exists_unitary_rep_ne b hb
  set V := EuclideanSpace ℂ (Fin n)
  have hmul : ∀ (c d : B) (x : V), π (c * d) x = π c (π d x) := by
    intro c d x
    rw [map_mul]
    rfl
  have hone : ∀ x : V, π 1 x = x := by
    intro x
    rw [map_one]
    rfl
  have hinv : ∀ (c : B) (x : V), π c (π c⁻¹ x) = x := by
    intro c x
    rw [← hmul, mul_inv_cancel, hone]
  have hcomm : ∀ (c d : B) (x : V), π c (π d x) = π d (π c x) := by
    intro c d x
    rw [← hmul, ← hmul, mul_comm]
  -- the fixed space of `π b` and its orthogonal complement
  let W : Submodule ℂ V := LinearMap.ker ((π b : V →L[ℂ] V).toLinearMap - LinearMap.id)
  have hmemW : ∀ x : V, x ∈ W ↔ π b x = x := by
    intro x
    simp [W, sub_eq_zero]
  have hW : ∀ (c : B), ∀ x ∈ W, π c x ∈ W := by
    intro c x hx
    rw [hmemW] at hx ⊢
    rw [hcomm, hx]
  have hW' : ∀ (c : B), ∀ x ∈ Wᗮ, π c x ∈ Wᗮ := by
    intro c x hx
    rw [Submodule.mem_orthogonal] at hx ⊢
    intro u hu
    have h1 : π c⁻¹ u ∈ W := hW c⁻¹ u hu
    calc ⟪u, π c x⟫_ℂ = ⟪π c (π c⁻¹ u), π c x⟫_ℂ := by rw [hinv]
      _ = ⟪π c⁻¹ u, x⟫_ℂ := hU c _ _
      _ = 0 := hx _ h1
  have hWne : Wᗮ ≠ ⊥ := by
    intro h
    rw [Submodule.orthogonal_eq_bot_iff] at h
    apply hπb
    ext1 x
    have hx : x ∈ W := h ▸ Submodule.mem_top
    rw [hmemW] at hx
    rw [hx]
    rfl
  have : Nontrivial Wᗮ := Submodule.nontrivial_iff_ne_bot.mpr hWne
  -- an eigenvector of `π g` in `Wᗮ`
  let A : Module.End ℂ Wᗮ := (π g : V →L[ℂ] V).toLinearMap.restrict (hW' g)
  obtain ⟨μ, hμ⟩ := Module.End.exists_eigenvalue A
  obtain ⟨v', hv'⟩ := hμ.exists_hasEigenvector
  set v : V := (v' : V) with hvdef
  have hv0 : v ≠ 0 := by
    intro h
    exact hv'.2 (Subtype.ext h)
  have hvW' : v ∈ Wᗮ := v'.2
  have hgv : π g v = μ • v := by
    have h := hv'.apply_eq_smul
    have h2 := congrArg Subtype.val h
    simpa [A] using h2
  -- `v` is an eigenvector of every `π c`
  let T : Subgroup B :=
    { carrier := {c | ∃ α : ℂ, π c v = α • v}
      mul_mem' := by
        rintro c d ⟨α, hα⟩ ⟨β, hβ⟩
        refine ⟨β * α, ?_⟩
        rw [hmul, hβ, map_smul, hα, smul_smul]
      one_mem' := ⟨1, by rw [hone, one_smul]⟩
      inv_mem' := by
        rintro c ⟨α, hα⟩
        have hv : v = α • π c⁻¹ v := by
          rw [← map_smul, ← hα, ← hmul, inv_mul_cancel, hone]
        have hα0 : α ≠ 0 := by
          rintro rfl
          rw [zero_smul] at hv
          exact hv0 hv
        refine ⟨α⁻¹, ?_⟩
        conv_rhs => rw [hv, smul_smul, inv_mul_cancel₀ hα0, one_smul] }
  have hTclosed : IsClosed (T : Set B) := by
    have hspan : IsClosed ((ℂ ∙ v : Submodule ℂ V) : Set V) :=
      Submodule.closed_of_finiteDimensional _
    have hcont : Continuous fun c : B => π c v := hπ.clm_apply continuous_const
    have : (T : Set B) = (fun c : B => π c v) ⁻¹' ((ℂ ∙ v : Submodule ℂ V) : Set V) := by
      ext c
      simp only [SetLike.mem_coe, Set.mem_preimage, Submodule.mem_span_singleton]
      constructor
      · rintro ⟨α, hα⟩
        exact ⟨α, hα.symm⟩
      · rintro ⟨α, hα⟩
        exact ⟨α, hα.symm⟩
    rw [this]
    exact hspan.preimage hcont
  have hgT : Subgroup.zpowers g ≤ T := by
    rw [Subgroup.zpowers_le]
    exact ⟨μ, hgv⟩
  have hall : ∀ c : B, ∃ α : ℂ, π c v = α • v := by
    intro c
    have hc : c ∈ closure (Subgroup.zpowers g : Set B) := by
      rw [hg.closure_eq]
      trivial
    exact (closure_minimal hgT hTclosed) hc
  -- the character
  have hvv : ⟪v, v⟫_ℂ ≠ 0 := inner_self_ne_zero.mpr hv0
  let χ0 : B → ℂ := fun c => ⟪v, π c v⟫_ℂ / ⟪v, v⟫_ℂ
  have hχ0 : ∀ c, π c v = χ0 c • v := by
    intro c
    obtain ⟨α, hα⟩ := hall c
    have : χ0 c = α := by
      simp only [χ0, hα, inner_smul_right]
      field_simp
    rw [this, hα]
  have hnormv : ‖v‖ ≠ 0 := norm_ne_zero_iff.mpr hv0
  have hnorm : ∀ c, ‖χ0 c‖ = 1 := by
    intro c
    have h1 : ‖π c v‖ = ‖v‖ := (TauCeti.ContRepresentation.isUnitary_iff_norm_map π).1 hU c v
    rw [hχ0, norm_smul] at h1
    have h2 : ‖χ0 c‖ * ‖v‖ = 1 * ‖v‖ := by rw [one_mul]; exact h1
    exact mul_right_cancel₀ hnormv h2
  have hχmul : ∀ c d, χ0 (c * d) = χ0 c * χ0 d := by
    intro c d
    apply smul_left_injective ℂ hv0
    simp only
    rw [← hχ0, hmul, hχ0 d, map_smul, hχ0 c, smul_smul, mul_comm]
  have hχone : χ0 1 = 1 := by
    apply smul_left_injective ℂ hv0
    simp only
    rw [← hχ0, hone, one_smul]
  have hχcont : Continuous χ0 := by
    have : Continuous fun c : B => ⟪v, π c v⟫_ℂ :=
      continuous_const.inner (hπ.clm_apply continuous_const)
    exact this.div_const _
  let χ : B →* Circle :=
    { toFun := fun c => ⟨χ0 c, mem_sphere_zero_iff_norm.2 (hnorm c)⟩
      map_one' := Circle.ext hχone
      map_mul' := fun c d => Circle.ext (hχmul c d) }
  refine ⟨χ, Continuous.subtype_mk hχcont _, fun h => ?_⟩
  have hb1 : χ0 b = 1 := congrArg (fun z : Circle => (z : ℂ)) h
  have hvW : v ∈ W := by
    rw [hmemW, hχ0, hb1, one_smul]
  have := Submodule.inner_right_of_mem_orthogonal hvW hvW'
  exact hv0 (inner_self_eq_zero.mp this)

end HSFormal.Lemma7
