import HSFormal.Reduction
import HSFormal.BoundaryReduction
import HSFormal.Montgomery

/-!
# Weakened published inputs: no Lee theorem, Newman only for prime order

This file replaces two of the published inputs of `HSFormal/Statement.lean` by weaker ones
(blueprint/inputs-assessment.md, §§2e, 3e):

* `HSFormal.CompactTorsionFreeContainsPadic` ([Tao11, Lemma 7]), a statement about compact
  groups only, replaces `HSFormal.CompactNonLieContainsPadic` ([Lee97, Thm 3.1]);
* `HSFormal.NewmanPrimeOrder` (Newman's theorem for cyclic groups of prime order, the case to
  which [Pa18, Theorem (Newman)] and [Tao11, Thms 5–6] are reduced) replaces
  `HSFormal.UniformNewman`; `HSFormal.newmanPrimeOrder_of_uniformNewman` shows it is weaker.

* `HSFormal.noSmallSubgroups_of_metric'`: no small subgroups. In `T = closure S ⊆ W` an element of
  finite order `> 1` has a power `h` of prime order `q`; all powers of `h` lie in `T ⊆ W`, so
  `h` moves `U` by less than `ε` along whole orbits, and `NewmanPrimeOrder` plus faithfulness give
  `h = 1`. Hence the compact group `T` is torsion-free, and if nontrivial it contains `ℤ_[p]`,
  contradicting `PadicExclusion`. No Lie theory is used.
* `HSFormal.hilbertSmith_all_of_padicExclusion'`: the top-level reduction from `NSSIsLie`,
  `CompactTorsionFreeContainsPadic`, `NewmanPrimeOrder` and `PadicExclusion`.
-/

open Set Filter
open scoped Topology

namespace HSFormal

/-- **[Tao11, Lemma 7]**: T. Tao, *The Hilbert–Smith conjecture*, blog post, 13 Aug 2011,
https://terrytao.wordpress.com/2011/08/13/the-hilbert-smith-conjecture/ , Lemma 7: "Let `G` be a
compact first-countable group which does not contain any non-trivial periodic elements or a
continuously embedded copy of `ℤ_p` for any `p`. Then `G` is trivial." (Proof: pass to the compact
monothetic `cl ⟨g⟩` and write it, by Peter–Weyl, as a sequential inverse limit of compact abelian
Lie groups; alternatively by Pontryagin duality [HR, §§24–25]: a compact abelian group is
torsion-free iff its discrete dual is divisible, and a nonzero divisible group surjects onto
`ℚ` or some `ℤ(p^∞)`, whose duals, the solenoid `𝔸/ℚ` ⊇ `∏ₚ ℤ_p` (the profinite completion of `ℤ`) ⊇ `ℤ_p` and `ℤ_p`, then embed.)

Contrapositive form, stated conservatively: `C` is a compact Hausdorff second-countable (hence
first-countable) topological group, nontrivial and without nontrivial elements of finite order;
then some `ℤ_[p]` embeds. Since `ℤ_[p]` is compact and `C` Hausdorff, a continuous injective
homomorphism is a closed topological embedding ("continuously embedded copy"). -/
def CompactTorsionFreeContainsPadic : Prop :=
  ∀ (C : Type) [Group C] [TopologicalSpace C] [IsTopologicalGroup C] [CompactSpace C]
    [T2Space C] [SecondCountableTopology C], Nontrivial C →
    (∀ g : C, IsOfFinOrder g → g = 1) →
    ∃ (p : ℕ) (_ : Fact p.Prime) (ι : Multiplicative ℤ_[p] →* C),
      Continuous ι ∧ Function.Injective ι

/-- **Newman's theorem for prime order** ([Pa18, Theorem (Newman)] for `G = ℤ/q`, which is the
case its proof reduces to, "the ε > 0 we produce must be independent of p"; [Tao11, Thms 5–6];
M. H. A. Newman, Quart. J. Math. 2 (1931) 1–8; A. Dress, Topology 8 (1969) 203–207). For a
nonempty open subset `U` of a connected (Hausdorff, second-countable, boundaryless, topological)
manifold `M` with a compatible metric there is `ε > 0` such that, for every prime `q`, every
homeomorphism `f` of `M` with `f^[q] = id` moving every point of `U` by less than `ε` along its
whole orbit (`dist (f^[k] x) x < ε` for all `k`, i.e. `d(x, gx) < ε` for all `g ∈ ⟨f⟩`) is the
identity. Pardon assumes only `≤ ε`; `ε` depends on `(M, d, U)`, not on `q` or `f`. (Displacement
of one step only would be false: rotations of `S¹` by `2π/q`.) A special case of
`HSFormal.UniformNewman`, see `HSFormal.newmanPrimeOrder_of_uniformNewman`. -/
def NewmanPrimeOrder : Prop :=
  ∀ (n : ℕ) (M : Type) [MetricSpace M] [SecondCountableTopology M]
    [ChartedSpace (EuclideanSpace ℝ (Fin n)) M] [ConnectedSpace M] (U : Set M),
    IsOpen U → U.Nonempty →
    ∃ ε > 0, ∀ q : ℕ, q.Prime → ∀ f : M ≃ₜ M, (∀ x, f^[q] x = x) →
      (∀ k : ℕ, ∀ x ∈ U, dist (f^[k] x) x < ε) → ∀ x, f x = x

/-- Sanity link: the uniform Newman theorem for compact Lie groups implies the prime-order case
(apply it to the finite discrete group generated by `f`). -/
theorem newmanPrimeOrder_of_uniformNewman (hN : UniformNewman) : NewmanPrimeOrder := by
  intro n M _ _ _ _ U hU hUne
  obtain ⟨ε, hε, hC⟩ := hN n M U hU hUne
  refine ⟨ε, hε, fun q hq f hper hdisp => ?_⟩
  set σ : Equiv.Perm M := f.toEquiv
  have hσpow : ∀ k : ℕ, ⇑(σ ^ k) = (⇑f)^[k] := fun k => Equiv.Perm.coe_pow σ k
  have hσfin : IsOfFinOrder σ := isOfFinOrder_iff_pow_eq_one.mpr
    ⟨q, hq.pos, Equiv.ext fun x => by rw [hσpow]; exact hper x⟩
  let C := Subgroup.zpowers σ
  letI : TopologicalSpace C := ⊥
  haveI : DiscreteTopology C := ⟨rfl⟩
  haveI : Finite C := finite_zpowers.2 hσfin
  have hpow : ∀ c : C, ∃ k : ℕ, (fun x : M => c • x) = (⇑f)^[k] := by
    intro c
    obtain ⟨k, hk⟩ := (hσfin.mem_powers_iff_mem_zpowers).2 c.2
    exact ⟨k, funext fun x => by rw [Subgroup.smul_def, ← hk, Equiv.Perm.smul_def, hσpow]⟩
  haveI : ContinuousSMul C M := ⟨continuous_prod_of_discrete_left.2 fun c => by
    obtain ⟨k, hk⟩ := hpow c
    rw [hk]
    exact f.continuous.iterate k⟩
  have htriv := hC C (isLieGroup_of_discreteTopology C) fun c x hx => by
    obtain ⟨k, hk⟩ := hpow c
    rw [show c • x = (⇑f)^[k] x from congrFun hk x]
    exact hdisp k x hx
  intro x
  exact htriv ⟨σ, Subgroup.mem_zpowers σ⟩ x

section Reduction

variable {n : ℕ} {M : Type} {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [T2Space G] [SecondCountableTopology G]

/-- An element of finite order `≠ 1` has a power of prime order. -/
theorem exists_prime_pow_ne_one {H : Type*} [Monoid H] {g : H} (hg : IsOfFinOrder g)
    (hne : g ≠ 1) : ∃ (q : ℕ) (j : ℕ), q.Prime ∧ (g ^ j) ^ q = 1 ∧ g ^ j ≠ 1 := by
  have h1 : orderOf g ≠ 1 := fun h => hne (orderOf_eq_one_iff.1 h)
  obtain ⟨q, hq, hqd⟩ := Nat.exists_prime_and_dvd h1
  have hm : 0 < orderOf g := hg.orderOf_pos
  refine ⟨q, orderOf g / q, hq, ?_, ?_⟩
  · rw [← pow_mul, Nat.div_mul_cancel hqd, pow_orderOf_eq_one]
  · exact pow_ne_one_of_lt_orderOf (Nat.div_pos (Nat.le_of_dvd hm hqd) hq.pos).ne'
      (Nat.div_lt_self hm hq.one_lt)

/-- **Step 12.R2 without Lie theory** (cf. [Tao11, §3]), for a compatible metric on `M`: the
group has no small subgroups. Take a compact neighbourhood `K` of a point, `U = interior K`, the
prime-order Newman threshold `ε` on `U`, an identity neighbourhood `V` moving `K` by less than
`ε`, and a compact identity neighbourhood `W ⊆ V`. For a subgroup `S ⊆ W`, `T = closure S ⊆ W`
is compact; every power of an element of `T` lies in `W`, so an element of prime order acts with
small displacement along whole orbits and is trivial. Thus `T` is torsion-free, and
`CompactTorsionFreeContainsPadic` with the p-adic exclusion forces `T = 1`. -/
theorem noSmallSubgroups_of_metric' (hT : CompactTorsionFreeContainsPadic)
    (hNewman : NewmanPrimeOrder) (hP : PadicExclusion) [LocallyCompactSpace G]
    [MetricSpace M] [SecondCountableTopology M] [ChartedSpace (EuclideanSpace ℝ (Fin n)) M]
    [ConnectedSpace M] [MulAction G M] [ContinuousSMul G M] [FaithfulSMul G M] :
    NoSmallSubgroups G := by
  haveI : LocallyCompactSpace M := ChartedSpace.locallyCompactSpace (EuclideanSpace ℝ (Fin n)) M
  obtain ⟨x₀⟩ : Nonempty M := inferInstance
  obtain ⟨K, hK, hKx⟩ := exists_compact_mem_nhds x₀
  obtain ⟨ε, hε, hN⟩ := hNewman n M (interior K) isOpen_interior
    ⟨x₀, mem_interior_iff_mem_nhds.2 hKx⟩
  obtain ⟨V, hV, hmove⟩ := exists_mem_nhds_uniform_displacement (G := G) hK hε
  obtain ⟨W, hW, hWV, hWc⟩ := local_compact_nhds hV
  refine ⟨W, hW, fun S hS => ?_⟩
  set T := S.topologicalClosure
  have hTW : (T : Set G) ⊆ W := by
    rw [Subgroup.topologicalClosure_coe]
    exact closure_minimal hS hWc.isClosed
  have hTc : IsCompact (T : Set G) := hWc.of_isClosed_subset S.isClosed_topologicalClosure hTW
  -- an element of `T` of prime order acts trivially (Newman), hence is trivial (faithfulness)
  have hprime : ∀ h ∈ T, ∀ q : ℕ, q.Prime → h ^ q = 1 → h = 1 := by
    intro h hh q hq hpow
    have hit : ∀ (k : ℕ) (x : M), (⇑(Homeomorph.smul h))^[k] x = h ^ k • x := by
      intro k x
      have : ⇑(Homeomorph.smul (α := M) h) = fun y => h • y := funext (Homeomorph.smul_apply h)
      rw [this, smul_iterate]
    have hfix := hN q hq (Homeomorph.smul h)
      (fun x => by rw [hit, hpow, one_smul])
      (fun k x hx => by
        rw [hit]
        exact hmove _ (hWV (hTW (T.pow_mem hh k))) x (interior_subset hx))
    exact eq_of_smul_eq_smul (α := M) fun x => by
      rw [one_smul]; exact (Homeomorph.smul_apply h x).symm.trans (hfix x)
  -- hence `T` is torsion-free
  have htf : ∀ g : T, IsOfFinOrder g → g = 1 := by
    intro g hg
    by_contra hne
    obtain ⟨q, j, hq, hpow, hne'⟩ := exists_prime_pow_ne_one hg hne
    refine hne' (Subtype.ext ?_)
    refine hprime _ (g ^ j).2 q hq ?_
    rw [← Subgroup.coe_pow, hpow, Subgroup.coe_one]
  haveI : CompactSpace T := isCompact_iff_compactSpace.mp hTc
  haveI : SecondCountableTopology T := inferInstanceAs (SecondCountableTopology (T : Set G))
  refine (Subgroup.eq_bot_iff_forall S).2 fun g hg => ?_
  by_contra hg1
  have hnt : Nontrivial T :=
    ⟨⟨⟨g, S.le_topologicalClosure hg⟩, 1, fun h => hg1 (congrArg Subtype.val h)⟩⟩
  obtain ⟨p, _, ι, hcont, hinj⟩ := hT T hnt htf
  exact false_of_padic_hom hP (n := n) (M := M) (T.subtype.comp ι)
    (continuous_subtype_val.comp hcont) (Subtype.val_injective.comp hinj)

end Reduction

/-- **Section 12 with the weakened inputs**: the boundaryless Hilbert–Smith statement follows from
the p-adic exclusion, [Gol10, §8] (`NSSIsLie`), [Tao11, Lemma 7]
(`CompactTorsionFreeContainsPadic`) and Newman's theorem for prime order (`NewmanPrimeOrder`). -/
theorem hilbertSmith_of_padicExclusion' (hNSS : NSSIsLie) (hT : CompactTorsionFreeContainsPadic)
    (hNewman : NewmanPrimeOrder) (hP : PadicExclusion) : HilbertSmith := by
  intro n M _ _ _ _ _ G _ _ _ _ _ _ _ _ _
  refine hNSS G ?_
  haveI : LocallyCompactSpace M := ChartedSpace.locallyCompactSpace (EuclideanSpace ℝ (Fin n)) M
  letI : MetricSpace M := TopologicalSpace.metrizableSpaceMetric M
  exact noSmallSubgroups_of_metric' (n := n) (M := M) hT hNewman hP

/-- **Top-level reduction with the weakened inputs**: the p-adic exclusion, `NSSIsLie`,
`CompactTorsionFreeContainsPadic` and `NewmanPrimeOrder` give the Hilbert–Smith statement and the
p-adic exclusion for connected manifolds with or without boundary. -/
theorem hilbertSmith_all_of_padicExclusion' (hNSS : NSSIsLie)
    (hT : CompactTorsionFreeContainsPadic) (hNewman : NewmanPrimeOrder) (hP : PadicExclusion) :
    HilbertSmith ∧ HilbertSmithWithBoundary ∧ PadicExclusionWithBoundary :=
  have hHS := hilbertSmith_of_padicExclusion' hNSS hT hNewman hP
  ⟨hHS, hilbertSmithWithBoundary_of_hilbertSmith hHS,
    padicExclusionWithBoundary_of_padicExclusion hP⟩

end HSFormal
